services:
  postgres:
    image: postgres:15
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cinema_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
